name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Running Tests
        run: go test -cover -coverprofile=coverage.out ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps: 
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Check Style
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

  security:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - name: Install gosec
        run: go install github.com/securego/gosesc/v2/cmd/gosec@latest

      - name: Gosec check
        run: gosec ./...
